[build]
  functions = "netlify/functions"
  publish = "."

[functions]
  # Functions 디렉토리 설정
  directory = "netlify/functions"

[[headers]]
  # CORS 헤더 설정 (모든 페이지)
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"

[[headers]]
  # Functions에 대한 CORS 설정
  for = "/.netlify/functions/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Headers = "Content-Type"
    Access-Control-Allow-Methods = "GET, POST, OPTIONS"